### ISSUE TITLE
flask_codemirror.CodeMirrorConfigException: CODEMIRROR_LANGUAGES is required

### ISSUE THREAD

**Issue by zappfinger** [j0ack/flask-codemirror#1]
I followed the example, installed with pip. But when I run my program I get the above error. I did not download any codemirror.js or similar, maybe that's the issue?

**Comment by j0ack** [comment]
Hello,
As the error said you need to initialize the CODEMIRROR_LANGUAGES config key in your app.

Please refer to the doc : [http://flask-codemirror.readthedocs.org/en/latest/](http://flask-codemirror.readthedocs.org/en/latest/).

The Javascript classes are imported from a CDN, there is no need to download any files.

Please feel free to tell me if it resolves your problem.

**Comment by zappfinger** [comment]
My bad, I did not have the config item right, so that was it.
Thanks!

Richard

**Comment by j0ack** [comment]
No problem,

Feel free to open a new ticket if you find any bug or have an idea for a new feature.
