### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by daveyman123** [j0ack/flask-codemirror#12]
I cant get the imports to work any more. no matter what I change them to they don't allow me to import.

No module named ext.codemirror.fields

**Comment by j0ack** [comment]
You're right the doc is out of date. Flask changed its way to import extension, you can replace the given example

```python
from flask.ext.codemirror import CodeMirror
```
by 

```python
from flask_codemirror import CodeMirror
```

I'll update the doc later
