### ISSUE TITLE
how can i defined the languages  for sql or mysql

### ISSUE THREAD

**Issue by linzh17** [j0ack/flask-codemirror#13]
how can i defined the languages  for sql or mysql
thx

**Comment by j0ack** [comment]
To see what modes are supported you can refer to codemirror website.

For sql in particular please see this page which defines what modes are supported https://codemirror.net/mode/sql/index.html

**Comment by linzh17** [comment]
i had initialized CODEMIRROR_LANGUAGES = ['sql'],but is doesn't work, mybe something wrong with codemirror 
whatever thx for your answer
