### ISSUE TITLE
Codemirror not accepting CODEMIRROR_LANGUAGES

### ISSUE THREAD

**Issue by Normanras** [j0ack/flask-codemirror#17]
While I have my flask app in different files for organization, even if I add the `flask-codemirror` settings in my main `routes.py`, it still throws this error. Everything else is being followed according to the documentation. 

If I get a chance to try this plugin with a brand new flask project, I'll report back if that's more successful. Just not sure if anyone else has faced a similar issue.

**Comment by j0ack** [comment]
Hello @Normanras and thanks for the issue.

I'm not sure to understand what you mean when you tell that your flask app is in different files. However, the `CODEMIRROR_LANGUAGES` needs to be setted in your [app configuration](https://flask.palletsprojects.com/en/2.2.x/config/#configuration-handling) to be available for the plugin. If this key is not detected it will raise an error. 

If this is not your problem, please provide code samples about the app configuration and initialization

**Comment by Normanras** [comment]
I've been away from my workstation so I'll share the code when I get back, but I did set it up according to my config with my other keys/config settings etc. I'll circle back.
