### ISSUE TITLE
use flask-codemirror with flask-admin

### ISSUE THREAD

**Issue by htlcnn** [j0ack/flask-codemirror#7]
I am wondering how to use flask-codemirror with a field in flask-admin ModelView. Could you please help me? Thanks very much!

**Comment by j0ack** [comment]
Hi,
I am not familiar with flask-admin but after reading the doc I suppose that you will need to create your own custom ModelView to integrate a new field type
https://flask-admin.readthedocs.io/en/latest/introduction/#adding-your-own-views
