### ISSUE TITLE
Use codemirror without 'codemirror.include_codemirror()'

### ISSUE THREAD

**Issue by elhamdaoui** [j0ack/flask-codemirror#9]
Hello,
firstly, thank you for this plugin.
I have a bug when I want to use the static code mirror files in my platform. I know you used 'cdnjs codemirror', but I want all files to be included in my platform.
I tried several times but I was not successful.
---- Codemirror files (the theme is also imported) ----
![t1](https://user-images.githubusercontent.com/11622841/31313685-ade383c4-abe1-11e7-891e-f5d010ef5bb7.png)

---- Issue -----
![t2](https://user-images.githubusercontent.com/11622841/31313688-e028b48a-abe1-11e7-8f63-9b214e79c418.png)

Sorry for my vEnglish.
Thank you.

**Comment by j0ack** [comment]
Hello,

Sorry, I don't understand your issue here. 
Coulld you give me more details in your JS error ?

**Comment by elhamdaoui** [comment]
Hi,
In your plugin you use 
```
<head>
    {{ codemirror.include_codemirror() }}
  </head>
```
to include the Codemirror library from 'cdnjs', so I will work in localhost, I want to use the downloaded library for codemirror. But I can't do that with your plugin. The second screen show what I have after eleminate
```
<head>
    {{ codemirror.include_codemirror() }}
  </head>
```
and use the static files (Js Downloaded Codemirror)

**Comment by j0ack** [comment]
I can't see why you couldn't use static files instead of CDN files.

Are your js files well loaded in your browser ?

**Comment by elhamdaoui** [comment]
No, if I use the CDN files it's work.
But I want use the static files in Localhost without Internet, all files in my Host, and instead of using 'CDN Files' I want to use my Local 'static' files. But it does not work.
For example, downloading the CodeMirror library and putting it in the 'static' folder of my flask plugin.
But this does work, and when I use your Function 'include_codemirror()' it works very well.
I can't understand :(

**Comment by j0ack** [comment]
That's why I asked you if your dowloaded static files are well loaded in your browser. 
Could you check if the constructed files path is correct and if you do not have any 404 error on any of them ?

I think the issue is about how Flask load your static files and not the plugin itself.

**Comment by elhamdaoui** [comment]
May be.
Any way, thank you.

**Comment by dani-polani** [comment]
elhamdaoui , your css files are not properly linked to html. 
It should be done with link tag, not script. 
`<link rel="stylesheet" href="/static/css/codemirror.css">`
With that being said, local files work fine with the plugin. 
And for me it makes pages to load 10 times faster than with CDN (50-70 ms vs 900ms). Also files from CDN are not minified and codemirror.js is 314 kb. It's larger than jquery!

**Comment by elhamdaoui** [comment]
Hi Daniel,
I had the bug in Js files not the Css.
But when I called the "include_codemirror()" function it worked, if I remember :)
